# примеры API-запросов

@baseUrl = http://127.0.0.1:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 7d54f2d6420b8c16e7c854c9832fa80d1dcc01e5

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 642d806be872dd4aa48d28e8d78bae9c24c85244

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/6/
Content-Type: application/json
Authorization: Token 7d54f2d6420b8c16e7c854c9832fa80d1dcc01e5

{
  "status": "CLOSED"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=2
Authorization: Token 642d806be872dd4aa48d28e8d78bae9c24c85244
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2022-12-20
Authorization: Token 7d54f2d6420b8c16e7c854c9832fa80d1dcc01e5
Content-Type: application/json


###

# добавление объявления в избранное
POST {{baseUrl}}/advertisements/favourite/
Content-Type: application/json
Authorization: Token 7d54f2d6420b8c16e7c854c9832fa80d1dcc01e5

{
  "advertisement": 1
}


###

# просмотр избранного объявления
GET {{baseUrl}}/advertisements/favourite/
Content-Type: application/json
Authorization: Token 7d54f2d6420b8c16e7c854c9832fa80d1dcc01e5

{

}


###

# фильтрация по статусу объявления
GET {{baseUrl}}/advertisements/?search=closed
Content-Type: application/json
Authorization: Token 7d54f2d6420b8c16e7c854c9832fa80d1dcc01e5

{

}