# Generated by Django 4.1.2 on 2022-11-07 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_articlescope_article_alter_articlescope_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlescope',
            old_name='main',
            new_name='is_main',
        ),
    ]
